title: "Yannock Verne"
description: "Streamer, Imperial Geographic, photographe du Verse & SubOrbital Records."
url: "https://yannockverne.github.io"
baseurl: ""

# ----------- THEME -----------
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# ----------- NAVIGATION -----------
include:
  - _pages

# ----------- DEFAULT CONFIG FOR PAGES -----------
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar: false
      author_profile: false
      toc: false

# ----------- BUILD -----------
markdown: kramdown
# Images al√©atoires pour header
random_header_images:
  - /assets/images/header/bg1.png
  - /assets/images/header/bg2.png
  - /assets/images/header/bg3.png
  - /assets/images/header/bg4.png