title: "Yannock Verne"
description: "Streamer, Imperial Geographic, photographe du Verse & SubOrbital Records."
url: "https://yannockverne.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

sass:
  style: compressed

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar: false
      author_profile: false
      toc: false

markdown: kramdown

collections:
  logbook:
    output: false